SELECT
  COUNT(DISTINCT data.basicpatient) patient_cant,
  COUNT(DISTINCT data.patient) / COUNT(DISTINCT data.basicpatient) * 100 total_perc,
  COUNT(DISTINCT data.patient) total,
  COUNT(DISTINCT data.familyrecord) / COUNT(DISTINCT data.basicpatient) * 100 familyrecord_perc,
  COUNT(DISTINCT data.familyrecord) familyrecord,
  COUNT(DISTINCT data.dass21) / COUNT(DISTINCT data.basicpatient) * 100 dass21_perc,
  COUNT(DISTINCT data.dass21) dass21,
  COUNT(DISTINCT data.environment) / COUNT(DISTINCT data.basicpatient) * 100 environment_perc,
  COUNT(DISTINCT data.environment) environment,
  COUNT(DISTINCT data.geriatricdepression) / COUNT(DISTINCT data.basicpatient) * 100 geriatricdepression_perc,
  COUNT(DISTINCT data.geriatricdepression) geriatricdepression,
  COUNT(DISTINCT data.zarittscale) / COUNT(DISTINCT data.basicpatient) * 100 zarittscale_perc,
  COUNT(DISTINCT data.zarittscale) zarittscale,
  COUNT(DISTINCT data.sociocultural) / COUNT(DISTINCT data.basicpatient) * 100 sociocultural_perc,
  COUNT(DISTINCT data.sociocultural) sociocultural,
  COUNT(DISTINCT data.diabetes) / COUNT(DISTINCT data.basicpatient) * 100 diabetes_perc,
  COUNT(DISTINCT data.diabetes) diabetes,
  COUNT(DISTINCT data.hypertension) / COUNT(DISTINCT data.basicpatient) * 100 hypertension_perc,
  COUNT(DISTINCT data.hypertension) hypertension,
  COUNT(DISTINCT data.bornlifestyle) / COUNT(DISTINCT data.basicpatient) * 100 bornlifestyle_perc,
  COUNT(DISTINCT data.bornlifestyle) bornlifestyle,
  COUNT(DISTINCT data.childlifestyle) / COUNT(DISTINCT data.basicpatient) * 100 childlifestyle_perc,
  COUNT(DISTINCT data.childlifestyle) childlifestyle,
  COUNT(DISTINCT data.younglifestyle) / COUNT(DISTINCT data.basicpatient) * 100 younglifestyle_perc,
  COUNT(DISTINCT data.younglifestyle) younglifestyle,
  COUNT(DISTINCT data.babylifestyle) / COUNT(DISTINCT data.basicpatient) * 100 babylifestyle_perc,
  COUNT(DISTINCT data.babylifestyle) babylifestyle,
  COUNT(DISTINCT data.gynecology) / COUNT(DISTINCT data.basicpatient) * 100 gynecology_perc,
  COUNT(DISTINCT data.gynecology) gynecology,
  COUNT(DISTINCT data.healthcare) / COUNT(DISTINCT data.basicpatient) * 100 healthcare_perc,
  COUNT(DISTINCT data.healthcare) healthcare,
  COUNT(DISTINCT data.vitalsign) / COUNT(DISTINCT data.basicpatient) * 100 vitalsign_perc,
  COUNT(DISTINCT data.vitalsign) vitalsign,
  COUNT(DISTINCT data.genderviolence) / COUNT(DISTINCT data.basicpatient) * 100 genderviolence_perc,
  COUNT(DISTINCT data.genderviolence) genderviolence,
  COUNT(DISTINCT data.childvaccination) / COUNT(DISTINCT data.basicpatient) * 100 childvaccination_perc,
  COUNT(DISTINCT data.childvaccination) childvaccination,
  COUNT(DISTINCT data.youngvaccination) / COUNT(DISTINCT data.basicpatient) * 100 youngvaccination_perc,
  COUNT(DISTINCT data.youngvaccination) youngvaccination,
  COUNT(DISTINCT data.adultvaccination) / COUNT(DISTINCT data.basicpatient) * 100 adultvaccination_perc,
  COUNT(DISTINCT data.adultvaccination) adultvaccination,
  COUNT(DISTINCT data.eldervaccination) / COUNT(DISTINCT data.basicpatient) * 100 eldervaccination_perc,
  COUNT(DISTINCT data.eldervaccination) eldervaccination,
  COUNT(DISTINCT data.hopeless) / COUNT(DISTINCT data.basicpatient) * 100 hopeless_perc,
  COUNT(DISTINCT data.hopeless) hopeless
  FROM(
    SELECT
    bpd.id basicpatient,
    NULL patient,
    NULL familyrecord,
    NULL dass21,
    NULL environment,
    NULL geriatricdepression,
    NULL zarittscale,
    NULL ets,
    NULL sociocultural,
    NULL diabetes,
    NULL hypertension,
    NULL bornlifestyle,
    NULL childlifestyle,
    NULL younglifestyle,
    NULL babylifestyle,
    NULL gynecology,
    NULL healthcare,
    NULL vitalsign,
    NULL genderviolence,
    NULL childvaccination,
    NULL youngvaccination,
    NULL adultvaccination,
    NULL eldervaccination,
    NULL hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    GROUP BY bpd.id, bpd.municipio
  UNION
    SELECT
    NULL basicpatient,
    fd.id_patient patient,
    fd.id_patient familyrecord,
    NULL dass21,
    NULL environment,
    NULL geriatricdepression,
    NULL zarittscale,
    NULL ets,
    NULL sociocultural,
    NULL diabetes,
    NULL hypertension,
    NULL bornlifestyle,
    NULL childlifestyle,
    NULL younglifestyle,
    NULL babylifestyle,
    NULL gynecology,
    NULL healthcare,
    NULL vitalsign,
    NULL genderviolence,
    NULL childvaccination,
    NULL youngvaccination,
    NULL adultvaccination,
    NULL eldervaccination,
    NULL hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    JOIN familyrecorddata fd ON fd.id_patient = bpd.id
    GROUP BY fd.id_patient, bpd.municipio
  UNION
    SELECT
    NULL basicpatient,
    fd.id_patient patient,
    NULL familyrecord,
    fd.id_patient dass21,
    NULL environment,
    NULL geriatricdepression,
    NULL zarittscale,
    NULL ets,
    NULL sociocultural,
    NULL diabetes,
    NULL hypertension,
    NULL bornlifestyle,
    NULL childlifestyle,
    NULL younglifestyle,
    NULL babylifestyle,
    NULL gynecology,
    NULL healthcare,
    NULL vitalsign,
    NULL genderviolence,
    NULL childvaccination,
    NULL youngvaccination,
    NULL adultvaccination,
    NULL eldervaccination,
    NULL hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    JOIN dass21data fd ON fd.id_patient = bpd.id
    GROUP BY fd.id_patient, bpd.municipio
  UNION
    SELECT
    NULL basicpatient,
    fd.id_patient patient,
    NULL familyrecord,
    NULL dass21,
    fd.id_patient environment,
    NULL geriatricdepression,
    NULL zarittscale,
    NULL ets,
    NULL sociocultural,
    NULL diabetes,
    NULL hypertension,
    NULL bornlifestyle,
    NULL childlifestyle,
    NULL younglifestyle,
    NULL babylifestyle,
    NULL gynecology,
    NULL healthcare,
    NULL vitalsign,
    NULL genderviolence,
    NULL childvaccination,
    NULL youngvaccination,
    NULL adultvaccination,
    NULL eldervaccination,
    NULL hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    JOIN environmentdata fd ON fd.id_patient = bpd.id
    GROUP BY fd.id_patient, bpd.municipio
  UNION
    SELECT
    NULL basicpatient,
    fd.id_patient patient,
    NULL familyrecord,
    NULL dass21,
    NULL environment,
    fd.id_patient geriatricdepression,
    NULL zarittscale,
    NULL ets,
    NULL sociocultural,
    NULL diabetes,
    NULL hypertension,
    NULL bornlifestyle,
    NULL childlifestyle,
    NULL younglifestyle,
    NULL babylifestyle,
    NULL gynecology,
    NULL healthcare,
    NULL vitalsign,
    NULL genderviolence,
    NULL childvaccination,
    NULL youngvaccination,
    NULL adultvaccination,
    NULL eldervaccination,
    NULL hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    JOIN geriatricdepressiondata fd ON fd.id_patient = bpd.id
    GROUP BY fd.id_patient, bpd.municipio
  UNION
    SELECT
    NULL basicpatient,
    fd.id_patient patient,
    NULL familyrecord,
    NULL dass21,
    NULL environment,
    NULL geriatricdepression,
    fd.id_patient zarittscale,
    NULL ets,
    NULL sociocultural,
    NULL diabetes,
    NULL hypertension,
    NULL bornlifestyle,
    NULL childlifestyle,
    NULL younglifestyle,
    NULL babylifestyle,
    NULL gynecology,
    NULL healthcare,
    NULL vitalsign,
    NULL genderviolence,
    NULL childvaccination,
    NULL youngvaccination,
    NULL adultvaccination,
    NULL eldervaccination,
    NULL hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    JOIN zarittscaledata fd ON fd.id_patient = bpd.id
    GROUP BY fd.id_patient, bpd.municipio
  UNION
    SELECT
    NULL basicpatient,
    fd.id_patient patient,
    NULL familyrecord,
    NULL dass21,
    NULL environment,
    NULL geriatricdepression,
    NULL zarittscale,
    fd.id_patient ets,
    NULL sociocultural,
    NULL diabetes,
    NULL hypertension,
    NULL bornlifestyle,
    NULL childlifestyle,
    NULL younglifestyle,
    NULL babylifestyle,
    NULL gynecology,
    NULL healthcare,
    NULL vitalsign,
    NULL genderviolence,
    NULL childvaccination,
    NULL youngvaccination,
    NULL adultvaccination,
    NULL eldervaccination,
    NULL hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    JOIN etsdata fd ON fd.id_patient = bpd.id
    GROUP BY fd.id_patient, bpd.municipio
  UNION
    SELECT
    NULL basicpatient,
    fd.id_patient patient,
    NULL familyrecord,
    NULL dass21,
    NULL environment,
    NULL geriatricdepression,
    NULL zarittscale,
    NULL ets,
    fd.id_patient sociocultural,
    NULL diabetes,
    NULL hypertension,
    NULL bornlifestyle,
    NULL childlifestyle,
    NULL younglifestyle,
    NULL babylifestyle,
    NULL gynecology,
    NULL healthcare,
    NULL vitalsign,
    NULL genderviolence,
    NULL childvaccination,
    NULL youngvaccination,
    NULL adultvaccination,
    NULL eldervaccination,
    NULL hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    JOIN socioculturaldata fd ON fd.id_patient = bpd.id
    GROUP BY fd.id_patient, bpd.municipio
  UNION
    SELECT
    NULL basicpatient,
    fd.id_patient patient,
    NULL familyrecord,
    NULL dass21,
    NULL environment,
    NULL geriatricdepression,
    NULL zarittscale,
    NULL ets,
    NULL sociocultural,
    fd.id_patient diabetes,
    NULL hypertension,
    NULL bornlifestyle,
    NULL childlifestyle,
    NULL younglifestyle,
    NULL babylifestyle,
    NULL gynecology,
    NULL healthcare,
    NULL vitalsign,
    NULL genderviolence,
    NULL childvaccination,
    NULL youngvaccination,
    NULL adultvaccination,
    NULL eldervaccination,
    NULL hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    JOIN diabetesdata fd ON fd.id_patient = bpd.id
    GROUP BY fd.id_patient, bpd.municipio
  UNION
    SELECT
    NULL basicpatient,
    fd.id_patient patient,
    NULL familyrecord,
    NULL dass21,
    NULL environment,
    NULL geriatricdepression,
    NULL zarittscale,
    NULL ets,
    NULL sociocultural,
    NULL diabetes,
    fd.id_patient hypertension,
    NULL bornlifestyle,
    NULL childlifestyle,
    NULL younglifestyle,
    NULL babylifestyle,
    NULL gynecology,
    NULL healthcare,
    NULL vitalsign,
    NULL genderviolence,
    NULL childvaccination,
    NULL youngvaccination,
    NULL adultvaccination,
    NULL eldervaccination,
    NULL hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    JOIN hypertensiondata fd ON fd.id_patient = bpd.id
    GROUP BY fd.id_patient, bpd.municipio
  UNION
    SELECT
    NULL basicpatient,
    fd.id_patient patient,
    NULL familyrecord,
    NULL dass21,
    NULL environment,
    NULL geriatricdepression,
    NULL zarittscale,
    NULL ets,
    NULL sociocultural,
    NULL diabetes,
    NULL hypertension,
    fd.id_patient bornlifestyle,
    NULL childlifestyle,
    NULL younglifestyle,
    NULL babylifestyle,
    NULL gynecology,
    NULL healthcare,
    NULL vitalsign,
    NULL genderviolence,
    NULL childvaccination,
    NULL youngvaccination,
    NULL adultvaccination,
    NULL eldervaccination,
    NULL hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    JOIN bornlifestyledata fd ON fd.id_patient = bpd.id
    GROUP BY fd.id_patient, bpd.municipio
  UNION
    SELECT
    NULL basicpatient,
    fd.id_patient patient,
    NULL familyrecord,
    NULL dass21,
    NULL environment,
    NULL geriatricdepression,
    NULL zarittscale,
    NULL ets,
    NULL sociocultural,
    NULL diabetes,
    NULL hypertension,
    NULL bornlifestyle,
    fd.id_patient childlifestyle,
    NULL younglifestyle,
    NULL babylifestyle,
    NULL gynecology,
    NULL healthcare,
    NULL vitalsign,
    NULL genderviolence,
    NULL childvaccination,
    NULL youngvaccination,
    NULL adultvaccination,
    NULL eldervaccination,
    NULL hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    JOIN childlifestyledata fd ON fd.id_patient = bpd.id
    GROUP BY fd.id_patient, bpd.municipio
  UNION
    SELECT
    NULL basicpatient,
    fd.id_patient patient,
    NULL familyrecord,
    NULL dass21,
    NULL environment,
    NULL geriatricdepression,
    NULL zarittscale,
    NULL ets,
    NULL sociocultural,
    NULL diabetes,
    NULL hypertension,
    NULL bornlifestyle,
    NULL childlifestyle,
    fd.id_patient younglifestyle,
    NULL babylifestyle,
    NULL gynecology,
    NULL healthcare,
    NULL vitalsign,
    NULL genderviolence,
    NULL childvaccination,
    NULL youngvaccination,
    NULL adultvaccination,
    NULL eldervaccination,
    NULL hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    JOIN younglifestyledata fd ON fd.id_patient = bpd.id
    GROUP BY fd.id_patient, bpd.municipio
  UNION
    SELECT
    NULL basicpatient,
    fd.id_patient patient,
    NULL familyrecord,
    NULL dass21,
    NULL environment,
    NULL geriatricdepression,
    NULL zarittscale,
    NULL ets,
    NULL sociocultural,
    NULL diabetes,
    NULL hypertension,
    NULL bornlifestyle,
    NULL childlifestyle,
    NULL younglifestyle,
    fd.id_patient babylifestyle,
    NULL gynecology,
    NULL healthcare,
    NULL vitalsign,
    NULL genderviolence,
    NULL childvaccination,
    NULL youngvaccination,
    NULL adultvaccination,
    NULL eldervaccination,
    NULL hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    JOIN babylifestyledata fd ON fd.id_patient = bpd.id
    GROUP BY fd.id_patient, bpd.municipio
  UNION
    SELECT
    NULL basicpatient,
    fd.id_patient patient,
    NULL familyrecord,
    NULL dass21,
    NULL environment,
    NULL geriatricdepression,
    NULL zarittscale,
    NULL ets,
    NULL sociocultural,
    NULL diabetes,
    NULL hypertension,
    NULL bornlifestyle,
    NULL childlifestyle,
    NULL younglifestyle,
    NULL babylifestyle,
    fd.id_patient gynecology,
    NULL healthcare,
    NULL vitalsign,
    NULL genderviolence,
    NULL childvaccination,
    NULL youngvaccination,
    NULL adultvaccination,
    NULL eldervaccination,
    NULL hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    JOIN gynecologydata fd ON fd.id_patient = bpd.id
    GROUP BY fd.id_patient, bpd.municipio
  UNION
    SELECT
    NULL basicpatient,
    fd.id_patient patient,
    NULL familyrecord,
    NULL dass21,
    NULL environment,
    NULL geriatricdepression,
    NULL zarittscale,
    NULL ets,
    NULL sociocultural,
    NULL diabetes,
    NULL hypertension,
    NULL bornlifestyle,
    NULL childlifestyle,
    NULL younglifestyle,
    NULL babylifestyle,
    NULL gynecology,
    fd.id_patient healthcare,
    NULL vitalsign,
    NULL genderviolence,
    NULL childvaccination,
    NULL youngvaccination,
    NULL adultvaccination,
    NULL eldervaccination,
    NULL hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    JOIN healthcaredata fd ON fd.id_patient = bpd.id
    GROUP BY fd.id_patient, bpd.municipio
  UNION
    SELECT
    NULL basicpatient,
    fd.id_patient patient,
    NULL familyrecord,
    NULL dass21,
    NULL environment,
    NULL geriatricdepression,
    NULL zarittscale,
    NULL ets,
    NULL sociocultural,
    NULL diabetes,
    NULL hypertension,
    NULL bornlifestyle,
    NULL childlifestyle,
    NULL younglifestyle,
    NULL babylifestyle,
    NULL gynecology,
    NULL healthcare,
    fd.id_patient vitalsign,
    NULL genderviolence,
    NULL childvaccination,
    NULL youngvaccination,
    NULL adultvaccination,
    NULL eldervaccination,
    NULL hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    JOIN vitalsigndata fd ON fd.id_patient = bpd.id
    GROUP BY fd.id_patient, bpd.municipio
  UNION
    SELECT
    NULL basicpatient,
    fd.id_patient patient,
    NULL familyrecord,
    NULL dass21,
    NULL environment,
    NULL geriatricdepression,
    NULL zarittscale,
    NULL ets,
    NULL sociocultural,
    NULL diabetes,
    NULL hypertension,
    NULL bornlifestyle,
    NULL childlifestyle,
    NULL younglifestyle,
    NULL babylifestyle,
    NULL gynecology,
    NULL healthcare,
    NULL vitalsign,
    fd.id_patient genderviolence,
    NULL childvaccination,
    NULL youngvaccination,
    NULL adultvaccination,
    NULL eldervaccination,
    NULL hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    JOIN genderviolencedata fd ON fd.id_patient = bpd.id
    GROUP BY fd.id_patient, bpd.municipio
  UNION
    SELECT
    NULL basicpatient,
    fd.id_patient patient,
    NULL familyrecord,
    NULL dass21,
    NULL environment,
    NULL geriatricdepression,
    NULL zarittscale,
    NULL ets,
    NULL sociocultural,
    NULL diabetes,
    NULL hypertension,
    NULL bornlifestyle,
    NULL childlifestyle,
    NULL younglifestyle,
    NULL babylifestyle,
    NULL gynecology,
    NULL healthcare,
    NULL vitalsign,
    NULL genderviolence,
    fd.id_patient childvaccination,
    NULL youngvaccination,
    NULL adultvaccination,
    NULL eldervaccination,
    NULL hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    JOIN childvaccinationdata fd ON fd.id_patient = bpd.id
    GROUP BY fd.id_patient, bpd.municipio
  UNION
    SELECT
    NULL basicpatient,
    fd.id_patient patient,
    NULL familyrecord,
    NULL dass21,
    NULL environment,
    NULL geriatricdepression,
    NULL zarittscale,
    NULL ets,
    NULL sociocultural,
    NULL diabetes,
    NULL hypertension,
    NULL bornlifestyle,
    NULL childlifestyle,
    NULL younglifestyle,
    NULL babylifestyle,
    NULL gynecology,
    NULL healthcare,
    NULL vitalsign,
    NULL genderviolence,
    NULL childvaccination,
    fd.id_patient youngvaccination,
    NULL adultvaccination,
    NULL eldervaccination,
    NULL hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    JOIN youngvaccinationdata fd ON fd.id_patient = bpd.id
    GROUP BY fd.id_patient, bpd.municipio
  UNION
    SELECT
    NULL basicpatient,
    fd.id_patient patient,
    NULL familyrecord,
    NULL dass21,
    NULL environment,
    NULL geriatricdepression,
    NULL zarittscale,
    NULL ets,
    NULL sociocultural,
    NULL diabetes,
    NULL hypertension,
    NULL bornlifestyle,
    NULL childlifestyle,
    NULL younglifestyle,
    NULL babylifestyle,
    NULL gynecology,
    NULL healthcare,
    NULL vitalsign,
    NULL genderviolence,
    NULL childvaccination,
    NULL youngvaccination,
    fd.id_patient adultvaccination,
    NULL eldervaccination,
    NULL hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    JOIN adultvaccinationdata fd ON fd.id_patient = bpd.id
    GROUP BY fd.id_patient, bpd.municipio
  UNION
    SELECT
    NULL basicpatient,
    fd.id_patient patient,
    NULL familyrecord,
    NULL dass21,
    NULL environment,
    NULL geriatricdepression,
    NULL zarittscale,
    NULL ets,
    NULL sociocultural,
    NULL diabetes,
    NULL hypertension,
    NULL bornlifestyle,
    NULL childlifestyle,
    NULL younglifestyle,
    NULL babylifestyle,
    NULL gynecology,
    NULL healthcare,
    NULL vitalsign,
    NULL genderviolence,
    NULL childvaccination,
    NULL youngvaccination,
    NULL adultvaccination,
    fd.id_patient eldervaccination,
    NULL hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    JOIN eldervaccinationdata fd ON fd.id_patient = bpd.id
    GROUP BY fd.id_patient, bpd.municipio
  UNION
    SELECT
    NULL basicpatient,
    fd.id_patient patient,
    NULL familyrecord,
    NULL dass21,
    NULL environment,
    NULL geriatricdepression,
    NULL zarittscale,
    NULL ets,
    NULL sociocultural,
    NULL diabetes,
    NULL hypertension,
    NULL bornlifestyle,
    NULL childlifestyle,
    NULL younglifestyle,
    NULL babylifestyle,
    NULL gynecology,
    NULL healthcare,
    NULL vitalsign,
    NULL genderviolence,
    NULL childvaccination,
    NULL youngvaccination,
    NULL adultvaccination,
    NULL eldervaccination,
    fd.id_patient hopeless,
    bpd.municipio
    FROM basicpatientdata bpd
    JOIN hopelessdata fd ON fd.id_patient = bpd.id
    GROUP BY fd.id_patient, bpd.municipio
  ) AS data WHERE data.municipio LIKE '%TEAPA%';