SELECT
  COUNT(`patient`) AS `total`,
  COUNT(DISTINCT `basicpatient`) AS `patient_cant`,
  ((COUNT(DISTINCT `patient`) / COUNT(DISTINCT `basicpatient`)) * 100) AS `total_perc`,
  COUNT(DISTINCT `patient`) AS `cont`,
  COUNT(DISTINCT `familyrecord`) AS `familyrecord`,
  COUNT(DISTINCT `dass21`) AS `dass21`,
  COUNT(DISTINCT `environment`) AS `environment`,
  COUNT(DISTINCT `geriatricdepression`) AS `geriatricdepression`,
  COUNT(DISTINCT `zarittscale`) AS `zarittscale`,
  COUNT(DISTINCT `ets`) AS `ets`,
  COUNT(DISTINCT `sociocultural`) AS `sociocultural`,
  COUNT(DISTINCT `diabetes`) AS `diabetes`,
  COUNT(DISTINCT `hypertension`) AS `hypertension`,
  COUNT(DISTINCT `bornlifestyle`) AS `bornlifestyle`,
  COUNT(DISTINCT `childlifestyle`) AS `childlifestyle`,
  COUNT(DISTINCT `younglifestyle`) AS `younglifestyle`,
  COUNT(DISTINCT `babylifestyle`) AS `babylifestyle`,
  COUNT(DISTINCT `gynecology`) AS `gynecology`,
  COUNT(DISTINCT `healthcare`) AS `healthcare`,
  COUNT(DISTINCT `vitalsign`) AS `vitalsign`,
  COUNT(DISTINCT `genderviolence`) AS `genderviolence`,
  COUNT(DISTINCT `childvaccination`) AS `childvaccination`,
  COUNT(DISTINCT `youngvaccination`) AS `youngvaccination`,
  COUNT(DISTINCT `adultvaccination`) AS `adultvaccination`,
  COUNT(DISTINCT `eldervaccination`) AS `eldervaccination`,
  COUNT(DISTINCT `hopeless`) AS `hopeless`
FROM dashboard_view
WHERE municipio = '__' OR municipio LIKE '%CENTRO%';